#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using Client.Map;
using Shared.World.Blocks;

namespace Client.Editor
{
    /// <summary>
    /// Кодоген Shared-зеркала каталога блоков: все BlockDefinition SO → BlockCatalogData.g.cs.
    /// Единственный легальный способ наполнить BlockCatalog (сервер SO не видит). С валидатором:
    /// при любой ошибке файл НЕ перезаписывается.
    /// </summary>
    public static class BlockCatalogCodegen
    {
        private const string OutputPath = "Assets/Scripts/Shared/World/Blocks/BlockCatalogData.g.cs";

        [MenuItem("Station/Blocks/Generate Block Catalog")]
        public static void Generate()
        {
            var defs = LoadAllDefinitions();
            if (!Validate(defs))
            {
                Debug.LogError("[BlockCatalogCodegen] Генерация отменена — исправьте ошибки выше.");
                return;
            }

            defs.Sort((a, b) => a.Type.CompareTo(b.Type));
            File.WriteAllText(OutputPath, Emit(defs), Encoding.UTF8);
            AssetDatabase.ImportAsset(OutputPath);
            BlockDefinitionResolver.Invalidate(); // визуальный кэш id→SO мог устареть вместе с каталогом
            Debug.Log($"[BlockCatalogCodegen] Сгенерировано типов: {defs.Count} → {OutputPath}");
        }

        public static List<BlockDefinition> LoadAllDefinitions()
        {
            var result = new List<BlockDefinition>();
            foreach (string guid in AssetDatabase.FindAssets("t:BlockDefinition"))
            {
                var def = AssetDatabase.LoadAssetAtPath<BlockDefinition>(AssetDatabase.GUIDToAssetPath(guid));
                if (def != null)
                    result.Add(def);
            }
            return result;
        }

        private static bool Validate(List<BlockDefinition> defs)
        {
            bool ok = true;
            var seen = new Dictionary<ushort, BlockDefinition>();

            foreach (var def in defs)
            {
                if (def.Type == 0)
                {
                    Debug.LogError($"[BlockCatalogCodegen] '{def.name}': id не назначен (0).", def);
                    ok = false;
                    continue;
                }
                if (seen.TryGetValue(def.Type, out var other))
                {
                    Debug.LogError($"[BlockCatalogCodegen] Дубль id {def.Type}: '{def.name}' и '{other.name}'.", def);
                    ok = false;
                }
                else
                {
                    seen[def.Type] = def;
                }

                var s = def.Size;
                if (s.x < 1 || s.y < 1 || s.z < 1 || s.x > 2 || s.y > 2 || s.z > 2
                    || s.x * s.y * s.z > Shared.World.Blocks.MultiBlock.MaxParts)
                {
                    Debug.LogError($"[BlockCatalogCodegen] '{def.name}': размер {s} недопустим (оси 1..2, частей ≤ 4).", def);
                    ok = false;
                }

                if (def.CollisionBoxes != null)
                {
                    foreach (var box in def.CollisionBoxes)
                    {
                        // Боксы авторятся в OBJECT-space [0..Size] и нарезаются кодогеном по частям.
                        Vector3 min = box.Center - box.Size * 0.5f;
                        Vector3 max = box.Center + box.Size * 0.5f;
                        if (min.x < -0.001f || min.y < -0.001f || min.z < -0.001f ||
                            max.x > s.x + 0.001f || max.y > s.y + 0.001f || max.z > s.z + 0.001f)
                        {
                            Debug.LogError($"[BlockCatalogCodegen] '{def.name}': бокс выходит за габарит объекта [0..{s.x}]×[0..{s.y}]×[0..{s.z}] (Size).", def);
                            ok = false;
                        }
                        if (Quant(max.x - min.x) <= 0 || Quant(max.y - min.y) <= 0 || Quant(max.z - min.z) <= 0)
                        {
                            Debug.LogError($"[BlockCatalogCodegen] '{def.name}': бокс вырождается при квантовании 1/16.", def);
                            ok = false;
                        }
                    }
                }
            }
            return ok;
        }

        private static int Quant(float v) => Mathf.Clamp(Mathf.RoundToInt(v * 16f), 0, 16);

        private static string Emit(List<BlockDefinition> defs)
        {
            var sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Генерируется BlockCatalogCodegen (Unity: Station/Blocks/Generate Block Catalog) из BlockDefinition SO.");
            sb.AppendLine("// НЕ править руками — файл перезаписывается целиком.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace Shared.World.Blocks");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class BlockCatalogData");
            sb.AppendLine("    {");
            sb.AppendLine("        internal static BlockInfo[] Build() => new BlockInfo[]");
            sb.AppendLine("        {");
            foreach (var def in defs)
                sb.AppendLine($"            {EmitEntry(def)},");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string EmitEntry(BlockDefinition def)
        {
            string name = (def.DisplayName ?? def.name).Replace("\\", "\\\\").Replace("\"", "\\\"");
            int sx = def.Size.x, sy = def.Size.y, sz = def.Size.z;
            int partCount = Shared.World.Blocks.MultiBlock.PartCount(sx, sy, sz);

            // Нарезка object-space боксов [0..Size] на ПЕР-ЧАСТЬ [0..1] (пересечение с кубом части).
            var perPart = new List<string>(partCount);
            for (int p = 0; p < partCount; p++)
            {
                Shared.World.Blocks.MultiBlock.PartToLocal(p, sx, sz, out int w, out int y, out int d);
                var slices = new List<string>();
                if (def.CollisionBoxes != null)
                    foreach (var box in def.CollisionBoxes)
                    {
                        Vector3 min = box.Center - box.Size * 0.5f;
                        Vector3 max = box.Center + box.Size * 0.5f;
                        float ix0 = Mathf.Max(min.x, w), ix1 = Mathf.Min(max.x, w + 1);
                        float iy0 = Mathf.Max(min.y, y), iy1 = Mathf.Min(max.y, y + 1);
                        float iz0 = Mathf.Max(min.z, d), iz1 = Mathf.Min(max.z, d + 1);
                        int qx0 = Quant(ix0 - w), qx1 = Quant(ix1 - w);
                        int qy0 = Quant(iy0 - y), qy1 = Quant(iy1 - y);
                        int qz0 = Quant(iz0 - d), qz1 = Quant(iz1 - d);
                        if (qx1 > qx0 && qy1 > qy0 && qz1 > qz0)
                            slices.Add($"new BlockBox({qx0}, {qy0}, {qz0}, {qx1}, {qy1}, {qz1})");
                    }
                perPart.Add(slices.Count == 0
                    ? "System.Array.Empty<BlockBox>()"
                    : $"new[] {{ {string.Join(", ", slices)} }}");
            }

            string boxes = $"new BlockBox[][] {{ {string.Join(", ", perPart)} }}";
            return $"new BlockInfo({def.Type}, \"{name}\", BlockCategory.{def.Category}, " +
                   $"(BlockFaceFlags){(byte)def.SealsFaces}, (BlockFaceFlags){(byte)def.OpaqueFaces}, " +
                   $"{def.DeconstructStages}, {boxes}, {sx}, {sy}, {sz})";
        }
    }
}
#endif
