// <auto-generated>
// Генерируется BlockCatalogCodegen (Unity: Station/Blocks/Generate Block Catalog) из BlockDefinition SO.
// НЕ править руками — файл перезаписывается целиком.
// </auto-generated>

namespace Shared.World.Blocks
{
    internal static class BlockCatalogData
    {
        internal static BlockInfo[] Build() => new BlockInfo[]
        {
            new BlockInfo(1, "Block", BlockCategory.Generic, (BlockFaceFlags)63, (BlockFaceFlags)63, 1, new BlockBox[][] { new[] { new BlockBox(0, 0, 0, 16, 16, 16) } }, 1, 1, 1),
            new BlockInfo(2, "Slab", BlockCategory.Floor, (BlockFaceFlags)63, (BlockFaceFlags)63, 1, new BlockBox[][] { new[] { new BlockBox(0, 12, 0, 16, 16, 16) } }, 1, 1, 1),
            new BlockInfo(3, "IronWall", BlockCategory.Wall, (BlockFaceFlags)63, (BlockFaceFlags)63, 0, new BlockBox[][] { new[] { new BlockBox(0, 0, 0, 16, 16, 16) }, new[] { new BlockBox(0, 0, 0, 16, 16, 16) } }, 1, 2, 1),
            new BlockInfo(4, "Floor", BlockCategory.Floor, (BlockFaceFlags)63, (BlockFaceFlags)63, 0, new BlockBox[][] { new[] { new BlockBox(0, 0, 0, 16, 16, 16) } }, 1, 1, 1),
        };
    }
}
